# Generated by Django 3.1.7 on 2021-04-25 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Description',
            field=models.CharField(max_length=150),
        ),
    ]
