# Generated by Django 3.1.7 on 2021-05-09 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_auto_20210425_2117'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='MUser',
        ),
    ]
