# Generated by Django 3.1.7 on 2021-05-18 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0006_muser_upload'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='values',
            new_name='value',
        ),
        migrations.AlterField(
            model_name='muser',
            name='Upload',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(max_length=1000),
        ),
    ]
