# Generated by Django 3.1.7 on 2021-05-18 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0007_auto_20210518_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='muser',
            name='Upload',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
